CREATE TABLE IF NOT EXISTS productos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  categoria VARCHAR(100) NOT NULL,
  descripcion VARCHAR(255),
  precio_unit DECIMAL(10,2) NOT NULL,
  stock INT NOT NULL DEFAULT 0,
  fecha_produccion DATE,
  fecha_caducidad DATE,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);